# Student: Simone Verhagen
# Studentnummer: 494729

services:
  web:
    build: ./web
    container_name: simone-web
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks: [appnet]

  redis:
    image: redis:alpine
    container_name: redis
    networks: [appnet]

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks: [appnet]

networks:
  appnet:
    driver: bridge
